FROM node:lts as dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install -f

FROM node:lts as builder
WORKDIR /app

# Declare build arguments for Azure and other service configurations
ARG AZURE_RESOURCE_NAME
ARG AZURE_API_KEY
ARG AZURE_API_VERSION
ARG AZURE_DEPLOYMENT_NAME
ARG AZURE_DEPLOYMENT_NAME_MINI
ARG AZURE_EMBEDDING_DEPLOYMENT_NAME
ARG MEMORY_DATABASE_URL
ARG GITHUB_TOKEN

# Set environment variables from build arguments
ENV NODE_ENV=production

# Set Azure and service configuration environment variables
ENV AZURE_RESOURCE_NAME=${AZURE_RESOURCE_NAME}
ENV AZURE_API_KEY=${AZURE_API_KEY}
ENV AZURE_API_VERSION=${AZURE_API_VERSION}
ENV AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
ENV AZURE_DEPLOYMENT_NAME_MINI=${AZURE_DEPLOYMENT_NAME_MINI}
ENV AZURE_EMBEDDING_DEPLOYMENT_NAME=${AZURE_EMBEDDING_DEPLOYMENT_NAME}
ENV MEMORY_DATABASE_URL=${MEMORY_DATABASE_URL}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

COPY ./ .
COPY --from=dependencies /app/node_modules ./node_modules

RUN yarn run build

FROM node:lts as runner
WORKDIR /app

# Declare runtime arguments
ARG AZURE_RESOURCE_NAME
ARG AZURE_API_KEY
ARG AZURE_API_VERSION
ARG AZURE_DEPLOYMENT_NAME
ARG AZURE_DEPLOYMENT_NAME_MINI
ARG AZURE_EMBEDDING_DEPLOYMENT_NAME
ARG MEMORY_DATABASE_URL
ARG GITHUB_TOKEN
ARG GROQ_API_KEY

# Set runtime environment variables
ENV AZURE_RESOURCE_NAME=${AZURE_RESOURCE_NAME}
ENV AZURE_API_KEY=${AZURE_API_KEY}
ENV AZURE_API_VERSION=${AZURE_API_VERSION}
ENV AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
ENV AZURE_DEPLOYMENT_NAME_MINI=${AZURE_DEPLOYMENT_NAME_MINI}
ENV AZURE_EMBEDDING_DEPLOYMENT_NAME=${AZURE_EMBEDDING_DEPLOYMENT_NAME}
ENV MEMORY_DATABASE_URL=${MEMORY_DATABASE_URL}
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

ENV HOSTNAME="0.0.0.0"
EXPOSE 4000

CMD ["npm", "run", "start"]