FROM node:lts as dependencies
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

FROM node:lts as builder
WORKDIR /app

# Declare build arguments for Azure and other service configurations
ARG AZURE_RESOURCE_NAME
ARG AZURE_API_KEY
ARG AZURE_API_VERSION
ARG AZURE_DEPLOYMENT_NAME
ARG AZURE_DEPLOYMENT_NAME_MINI
ARG AZURE_EMBEDDING_DEPLOYMENT_NAME
ARG MEMORY_DATABASE_URL
ARG PROFILE_G_TOKEN
ARG CALENDARIFIC_API_KEY
ARG ALLOWED_ORIGINS
ARG NEXT_PUBLIC_HASHNODE_HOST
ARG HASHNODE_PAT

# Set environment variables from build arguments
ENV NODE_ENV=production

# Set Azure and service configuration environment variables
ENV AZURE_RESOURCE_NAME=${AZURE_RESOURCE_NAME}
ENV AZURE_API_KEY=${AZURE_API_KEY}
ENV AZURE_API_VERSION=${AZURE_API_VERSION}
ENV AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
ENV AZURE_DEPLOYMENT_NAME_MINI=${AZURE_DEPLOYMENT_NAME_MINI}
ENV AZURE_EMBEDDING_DEPLOYMENT_NAME=${AZURE_EMBEDDING_DEPLOYMENT_NAME}
ENV MEMORY_DATABASE_URL=${MEMORY_DATABASE_URL}
ENV PROFILE_G_TOKEN=${PROFILE_G_TOKEN}
ENV CALENDARIFIC_API_KEY=${CALENDARIFIC_API_KEY}
ENV ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
ENV NEXT_PUBLIC_HASHNODE_HOST=${NEXT_PUBLIC_HASHNODE_HOST}
ENV HASHNODE_PAT=${HASHNODE_PAT}

COPY ./ .
COPY --from=dependencies /app/node_modules ./node_modules

# Build both Next.js and Mastra server
RUN npm run build

FROM node:lts as runner
WORKDIR /app

# Declare runtime arguments
ARG AZURE_RESOURCE_NAME
ARG AZURE_API_KEY
ARG AZURE_API_VERSION
ARG AZURE_DEPLOYMENT_NAME
ARG AZURE_DEPLOYMENT_NAME_MINI
ARG AZURE_EMBEDDING_DEPLOYMENT_NAME
ARG MEMORY_DATABASE_URL
ARG PROFILE_G_TOKEN
ARG CALENDARIFIC_API_KEY
ARG ALLOWED_ORIGINS
ARG NEXT_PUBLIC_HASHNODE_HOST
ARG HASHNODE_PAT

# Set runtime environment variables (needed for Mastra server)
ENV AZURE_RESOURCE_NAME=${AZURE_RESOURCE_NAME}
ENV AZURE_API_KEY=${AZURE_API_KEY}
ENV AZURE_API_VERSION=${AZURE_API_VERSION}
ENV AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
ENV AZURE_DEPLOYMENT_NAME_MINI=${AZURE_DEPLOYMENT_NAME_MINI}
ENV AZURE_EMBEDDING_DEPLOYMENT_NAME=${AZURE_EMBEDDING_DEPLOYMENT_NAME}
ENV MEMORY_DATABASE_URL=${MEMORY_DATABASE_URL}
ENV PROFILE_G_TOKEN=${PROFILE_G_TOKEN}
ENV CALENDARIFIC_API_KEY=${CALENDARIFIC_API_KEY}
ENV ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
ENV NEXT_PUBLIC_HASHNODE_HOST=${NEXT_PUBLIC_HASHNODE_HOST}
ENV HASHNODE_PAT=${HASHNODE_PAT}
ENV MASTRA_API_URL=http://localhost:4000
ENV MASTRA_PORT=4000

COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/mastra-server ./mastra-server
COPY --from=builder /app/start.sh ./start.sh
COPY --from=builder /app/src ./src

# Make start script executable
RUN chmod +x start.sh

ENV HOSTNAME="0.0.0.0"
# Only expose Next.js port - Mastra runs internally on 4000
EXPOSE 3000

CMD ["npm", "run", "start"]