packages:
  - "."

allowBuilds:
  "@ffmpeg-installer/linux-x64": true
  esbuild: true
  node-mic: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  "@mastra/node-speaker": false
  "@ffmpeg-installer/darwin-arm64": false

minimumReleaseAgeExclude:
  - '@dishant0406/dev-to@1.0.4'
