import { createTheme } from '@openuidev/react-ui'

// Keep OpenUI aligned with the app's existing CSS variables so the generated
// renderer automatically follows light/dark mode and brand accents.
export const portfolioOpenUITheme = createTheme({
  background: 'var(--color-background)',
  // OpenUI uses "foreground" as the default raised surface fill token.
  foreground: 'var(--color-card)',
  popoverBackground: 'var(--color-popover)',

  sunkLight: 'color-mix(in srgb, var(--color-secondary) 64%, var(--color-card))',
  sunk: 'var(--color-secondary)',
  sunkDeep: 'var(--color-accent)',
  elevatedLight: 'var(--color-card)',
  elevated: 'var(--color-card)',
  elevatedStrong: 'var(--color-card-hover)',
  elevatedIntense: 'var(--color-card-hover)',
  overlay: 'color-mix(in srgb, var(--color-overlay) 12%, transparent)',

  highlightSubtle: 'color-mix(in srgb, var(--color-secondary) 72%, var(--color-card))',
  highlight: 'color-mix(in srgb, var(--color-accent) 72%, var(--color-card))',
  highlightStrong: 'color-mix(in srgb, var(--color-accent) 84%, var(--color-card))',
  highlightIntense: 'var(--color-card-hover)',

  infoBackground: 'color-mix(in srgb, var(--color-info) 14%, var(--color-background))',
  successBackground: 'color-mix(in srgb, var(--color-success) 14%, var(--color-background))',
  alertBackground: 'color-mix(in srgb, var(--color-warning) 18%, var(--color-background))',
  dangerBackground: 'color-mix(in srgb, var(--color-destructive) 14%, var(--color-background))',
  purpleBackground: 'color-mix(in srgb, var(--color-chart-4) 18%, var(--color-background))',
  pinkBackground: 'color-mix(in srgb, var(--color-chart-2) 14%, var(--color-background))',

  textNeutralPrimary: 'var(--color-foreground)',
  textNeutralSecondary: 'var(--color-muted-foreground)',
  textNeutralTertiary: 'color-mix(in srgb, var(--color-muted-foreground) 78%, var(--color-background))',
  textNeutralLink: 'var(--color-link)',
  textBrand: 'var(--color-primary)',
  textWhite: 'rgb(255, 255, 255)',
  textBlack: 'rgb(10, 10, 10)',
  textAccentPrimary: 'var(--color-primary)',
  textAccentSecondary: 'var(--color-link)',
  textAccentTertiary: 'var(--color-link-hover)',
  textSuccessPrimary: 'var(--color-success)',
  textSuccessInverted: 'var(--color-success-foreground)',
  textAlertPrimary: 'var(--color-warning)',
  textAlertInverted: 'var(--color-warning-foreground)',
  textDangerPrimary: 'var(--color-destructive)',
  textDangerSecondary: 'color-mix(in srgb, var(--color-destructive) 80%, var(--color-foreground))',
  textDangerTertiary: 'color-mix(in srgb, var(--color-destructive) 60%, var(--color-foreground))',
  textDangerInvertedPrimary: 'var(--color-destructive-foreground)',
  textDangerInvertedSecondary: 'color-mix(in srgb, var(--color-destructive-foreground) 80%, transparent)',
  textDangerInvertedTertiary: 'color-mix(in srgb, var(--color-destructive-foreground) 64%, transparent)',
  textInfoPrimary: 'var(--color-info)',
  textInfoInverted: 'var(--color-info-foreground)',
  textPinkPrimary: 'var(--color-chart-2)',
  textPinkInverted: 'var(--color-primary-foreground)',
  textPurplePrimary: 'var(--color-chart-4)',
  textPurpleInverted: 'var(--color-primary-foreground)',

  interactiveAccentDefault: 'var(--color-primary)',
  interactiveAccentHover: 'color-mix(in srgb, var(--color-primary) 86%, var(--color-background))',
  interactiveAccentDisabled: 'var(--color-muted)',
  interactiveAccentPressed: 'color-mix(in srgb, var(--color-primary) 72%, var(--color-background))',
  interactiveDestructiveDefault: 'var(--color-destructive)',
  interactiveDestructiveHover: 'color-mix(in srgb, var(--color-destructive) 86%, var(--color-background))',
  interactiveDestructiveDisabled: 'color-mix(in srgb, var(--color-destructive) 28%, var(--color-background))',
  interactiveDestructivePressed: 'color-mix(in srgb, var(--color-destructive) 72%, var(--color-background))',
  interactiveDestructiveAccentDefault: 'var(--color-destructive)',
  interactiveDestructiveAccentHover: 'color-mix(in srgb, var(--color-destructive) 86%, var(--color-background))',
  interactiveDestructiveAccentPressed: 'color-mix(in srgb, var(--color-destructive) 72%, var(--color-background))',
  interactiveDestructiveAccentDisabled: 'color-mix(in srgb, var(--color-destructive) 28%, var(--color-background))',

  borderDefault: 'var(--color-border)',
  borderInteractive: 'var(--color-input)',
  borderInteractiveEmphasis: 'var(--color-ring)',
  borderInteractiveSelected: 'var(--color-primary)',
  borderAccent: 'var(--color-primary)',
  borderAccentEmphasis: 'color-mix(in srgb, var(--color-primary) 78%, var(--color-background))',
  borderAccentSelected: 'var(--color-primary)',
  borderInfo: 'color-mix(in srgb, var(--color-info) 42%, var(--color-background))',
  borderInfoEmphasis: 'var(--color-info)',
  borderAlert: 'color-mix(in srgb, var(--color-warning) 42%, var(--color-background))',
  borderAlertEmphasis: 'var(--color-warning)',
  borderSuccess: 'color-mix(in srgb, var(--color-success) 42%, var(--color-background))',
  borderSuccessEmphasis: 'var(--color-success)',
  borderDanger: 'color-mix(in srgb, var(--color-destructive) 42%, var(--color-background))',
  borderDangerEmphasis: 'var(--color-destructive)',

  chatUserResponseBg: 'var(--color-primary)',
  chatUserResponseText: 'var(--color-primary-foreground)',

  defaultChartPalette: [
    'var(--color-chart-1)',
    'var(--color-chart-2)',
    'var(--color-chart-3)',
    'var(--color-chart-4)',
    'var(--color-chart-5)',
  ],
  barChartPalette: [
    'var(--color-chart-2)',
    'var(--color-chart-3)',
    'var(--color-chart-4)',
    'var(--color-chart-5)',
  ],
  lineChartPalette: [
    'var(--color-chart-2)',
    'var(--color-chart-3)',
    'var(--color-chart-4)',
    'var(--color-chart-5)',
  ],
  areaChartPalette: [
    'var(--color-chart-1)',
    'var(--color-chart-2)',
    'var(--color-chart-3)',
  ],
  pieChartPalette: [
    'var(--color-chart-1)',
    'var(--color-chart-2)',
    'var(--color-chart-3)',
    'var(--color-chart-4)',
    'var(--color-chart-5)',
  ],
  radarChartPalette: [
    'var(--color-chart-2)',
    'var(--color-chart-3)',
    'var(--color-chart-4)',
  ],
  radialChartPalette: [
    'var(--color-chart-2)',
    'var(--color-chart-3)',
    'var(--color-chart-4)',
  ],
  horizontalBarChartPalette: [
    'var(--color-chart-2)',
    'var(--color-chart-3)',
    'var(--color-chart-4)',
  ],

  radius2xs: 'var(--radius-sm)',
  radiusXs: 'var(--radius-sm)',
  radiusS: 'var(--radius-md)',
  radiusM: 'var(--radius-lg)',
  radiusL: 'var(--radius-xl)',
  radiusFull: '9999px',

  fontBody: 'var(--font-sans)',
  fontHeading: 'var(--font-sans)',
  fontLabel: 'var(--font-sans)',
  fontCode: 'var(--font-mono)',
  fontNumbers: 'var(--font-sans)',

  shadow0: 'none',
  shadowS: 'var(--shadow-sm)',
  shadowM: 'var(--shadow)',
  shadowL: 'var(--shadow-md)',
  shadowXl: 'var(--shadow-lg)',
  shadow2xl: 'var(--shadow-xl)',
  shadow3xl: 'var(--shadow-2xl)',
})
